# Generated by Django 2.0.2 on 2018-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file_field',
        ),
    ]
